target 'Example' do
	use_frameworks!
	pod 'SwiftIconFont', :path => '../'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
